#!/usr/bin/env bash
# One-command install of Pulse (LIVE GEO NEWS) on a fresh Ubuntu/Debian VPS, run as root:
#
#   curl -fsSL https://raw.githubusercontent.com/Vishtal87/Vishtal87/claude/geo-news-interactive-map-29asu8/scripts/bootstrap-server.sh | bash
#
# Optional variables (put them before `bash`): DOMAIN=news.example.ru (default: <ip>.sslip.io, no domain needed),
# BRANCH, DIR (default /opt/pulse), AUTOUPDATE=0 (do not install the 30-minute auto-update timer).
# Safe to run again: existing .env and data are kept, finished steps are skipped.
# PULSE_DRY_RUN=1 shows the settings it would use and changes nothing.
set -euo pipefail

REPO=${REPO:-https://github.com/Vishtal87/Vishtal87.git}
BRANCH=${BRANCH:-claude/geo-news-interactive-map-29asu8}
DIR=${DIR:-/opt/pulse}
LOG=${LOG:-/var/log/pulse-install.log}
say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

public_ip() {
  local ip
  ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i < NF; i++) if ($i == "src") print $(i + 1)}')
  case "$ip" in 10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[01].*|100.6[4-9].*|100.[7-9][0-9].*|100.1[01][0-9].*|100.12[0-7].*|"")
    ip=$(curl -fsS4 --max-time 10 https://ifconfig.me 2>/dev/null || true) ;;
  esac
  echo "$ip"
}

mem_mb() { awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo; }
port_busy() { ss -Hltn "sport = :$1" | grep -q .; }
free_port() { for p in "$@"; do port_busy "$p" || { echo "$p"; return; }; done; echo "$1"; }

write_env() {   # prints a complete .env for this machine
  local ip=$1 domain=$2 mem=$3 shared cache workers
  if [ "$mem" -lt 3000 ]; then shared=512MB cache=1536MB workers=1
  elif [ "$mem" -lt 6000 ]; then shared=1GB cache=3GB workers=2
  else shared=2GB cache=6GB workers=4; fi
  cat <<EOF
# Generated by scripts/bootstrap-server.sh on $(date -u +%Y-%m-%d). Keep private. See .env.example for comments.
DOMAIN=$domain
PUBLIC_IP=$ip
POSTGRES_PASSWORD=$(openssl rand -hex 24)
GEONEWS_SOURCES=sources.ru.yaml
GEONEWS_USER_AGENT="GeoNewsBot/1.0 (+https://$domain)"
API_WORKERS=$workers
PG_SHARED_BUFFERS=$shared
PG_EFFECTIVE_CACHE=$cache
BACKUP_EVERY_HOURS=24
BACKUP_KEEP=7
EOF
}

# ------------------------------------------------------------------ dry run: show the plan only
if [ -n "${PULSE_DRY_RUN:-}" ]; then
  ip=$(public_ip); domain=${DOMAIN:-${ip//./-}.sslip.io}
  echo "would install $REPO@$BRANCH into $DIR, log $LOG, with .env:"
  write_env "$ip" "$domain" "$(mem_mb)" | sed 's/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=<random>/'
  exit 0
fi

[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo -i)"; exit 1; }

# ------------------------------------------------------------------ stage 1: code, then continue in the background
if [ "${1:-}" != "--install" ]; then
  say "Getting the code into $DIR"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq && apt-get install -y -qq git curl ca-certificates openssl iproute2 >/dev/null
  if [ -d "$DIR/.git" ]; then git -C "$DIR" fetch -q origin "$BRANCH" && git -C "$DIR" checkout -q "$BRANCH" \
    && git -C "$DIR" pull -q --ff-only origin "$BRANCH"
  else git clone -q -b "$BRANCH" "$REPO" "$DIR"; fi
  # the long part runs detached: closing this SSH window does not stop the installation
  setsid nohup bash "$DIR/scripts/bootstrap-server.sh" --install > "$LOG" 2>&1 < /dev/null &
  pid=$!
  say "Installation is running in the background (20-40 min). Progress below; Ctrl+C only stops watching."
  echo "    Watch again later: tail -f $LOG"
  tail --pid="$pid" -n +1 -f "$LOG" || true
  exit 0
fi

# ------------------------------------------------------------------ stage 2: install
cd "$DIR"
if ! command -v docker >/dev/null; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi

# docker-compose.prod.yml needs Compose v2.24+ (`!reset`); an older preinstalled Docker gets its plugin updated
cv=$(docker compose version --short 2>/dev/null || echo 0)
if [ "$(printf '%s\n2.24.0\n' "${cv#v}" | sort -V | head -1)" != "2.24.0" ]; then
  say "Updating Docker Compose ($cv is too old)"
  apt-get install -y -qq docker-compose-plugin >/dev/null || curl -fsSL https://get.docker.com | sh
fi

if [ "$(mem_mb)" -lt 3500 ] && [ "$(swapon --show --noheadings | wc -l)" -eq 0 ]; then
  say "Adding 2 GB swap (small server: keeps the database import from running out of memory)"
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

if [ ! -f .env ]; then
  ip=$(public_ip)
  [ -n "$ip" ] || { echo "could not detect the public IP: set DOMAIN and PUBLIC_IP in $DIR/.env and rerun"; exit 1; }
  write_env "$ip" "${DOMAIN:-${ip//./-}.sslip.io}" "$(mem_mb)" > .env
  chmod 600 .env
fi
set -a; . ./.env; set +a

say "Building and preparing the database (first time ~10-15 min)"
scripts/prod.sh init

if [ ! -f .geonames-RU.done ]; then
  say "Loading every settlement of Russia from GeoNames (~10-20 min)"
  scripts/prod.sh geonames RU && touch .geonames-RU.done
fi

say "Checking news sources (Krasnodar Krai, federal media)"
scripts/prod.sh verify-sources --keep-previous

# ports 80/443 held by something else (another site, a VPN panel): leave it alone and take free ports instead.
# "Something else" = anything but this installation's own Caddy (other projects may have a *-caddy-1 too).
our_caddy=$(docker compose -f docker-compose.yml -f docker-compose.prod.yml ps -q --status running caddy 2>/dev/null || true)
if ! grep -q '^HTTP_PORT=' .env && [ -z "$our_caddy" ] && { port_busy 80 || port_busy 443; }; then
  hp=$(free_port 8080 8081 8088 8888 8000); sp=$(free_port 8443 8444 9443)
  say "Ports 80/443 are already used by another service on this server: the site goes to port $hp"
  printf 'HTTP_PORT=%s\nHTTPS_PORT=%s\n' "$hp" "$sp" >> .env
fi
# no certificate can be obtained without ports 80/443: serve the domain over plain HTTP instead of failing attempts
if grep -q '^HTTP_PORT=' .env && ! grep -q '^HTTP_PORT=80$' .env && ! grep -q '^SITE_SCHEME=' .env; then
  echo 'SITE_SCHEME=http://' >> .env
fi
set -a; . ./.env; set +a

say "Starting the site"
scripts/prod.sh up
scripts/prod.sh health 18 || echo "the site is not answering yet: scripts/prod.sh logs caddy api"

if [ "${AUTOUPDATE:-1}" != 0 ]; then
  say "Installing auto-update (checks for new versions every 30 min, rolls back if the site breaks)"
  cat > /etc/systemd/system/pulse-autoupdate.service <<UNIT
[Unit]
Description=Pulse: apply new commits of $BRANCH (rolls back when the site is unhealthy)
After=docker.service network-online.target
Wants=network-online.target
[Service]
Type=oneshot
WorkingDirectory=$DIR
ExecStart=$DIR/scripts/prod.sh autoupdate
TimeoutStartSec=3600
UNIT
  cat > /etc/systemd/system/pulse-autoupdate.timer <<UNIT
[Unit]
Description=Pulse auto-update every 30 minutes
[Timer]
OnBootSec=10min
OnUnitActiveSec=30min
RandomizedDelaySec=120
[Install]
WantedBy=timers.target
UNIT
  systemctl daemon-reload && systemctl enable --now pulse-autoupdate.timer
fi

say "DONE"
if [ "${HTTP_PORT:-80}" = 80 ]; then
  echo "    Site:           https://$DOMAIN"
  echo "    Also (no TLS):  http://$PUBLIC_IP"
else
  echo "    Site:           http://$PUBLIC_IP:$HTTP_PORT   (ports 80/443 are used by another service, so no HTTPS)"
  echo "    Also:           http://$DOMAIN:$HTTP_PORT"
fi
echo "    First news appear within ~5 minutes. Manage with: cd $DIR && scripts/prod.sh status|logs|update|backup"
[ "${AUTOUPDATE:-1}" = 0 ] || echo "    Auto-update log: journalctl -u pulse-autoupdate   Off: systemctl disable --now pulse-autoupdate.timer"
echo "    Security: change the root password (passwd) or switch to SSH keys."
